### ISSUE TITLE
更新host 网址出错

### ISSUE THREAD

**Issue by quegfeng** [ZzzM/HostToolforMac#10]
貌似https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts 已被删，没有 swift3，没法自编译修改源码，能否自定义增加自定义 host 更新网址。谢谢！

**Comment by ZzzM** [comment]
@quegfeng 多谢你的反馈，我会尽快替换为有效的hosts地址，你建议添加的功能，后续我也会考虑增加。
