### ISSUE TITLE
更新后还是会覆盖hosts中自定义的ip

### ISSUE THREAD

**Issue by 5star2014** [ZzzM/HostToolforMac#11]
如题，不知道是否方法不对。

**Comment by ZzzM** [comment]
你是手动更新的话，是会覆盖。

自动更新的话，规则如下：
------------------------------------------------
（不能写）
# Copyright (c) 2014-2016, racaljk.
（不能写）
fe80::1%lo0	localhost
（可以添加在这里）
# Modified hosts start
（不能写）
# Modified hosts end
（可以添加在这里）
------------------------------------------------
