### ISSUE TITLE
为什么最近自动更新又会导致闪退

### ISSUE THREAD

**Issue by pjpjq** [ZzzM/HostToolforMac#13]
我之前把 hosts 内容清空了, 然后今天用自动更新会闪退. 之后下载 hosts 手动更新成功, 然后再自动更新就不会闪退了.

**Comment by ZzzM** [comment]
@wendingp 你目前用的是最新的版本（v2.1.0）吗？

**Comment by pjpjq** [comment]
是的

**Comment by ZzzM** [comment]
我上午清空了hosts，点自动更新没有发生闪退。我再看看

**Comment by ZzzM** [comment]
@wendingp 目前版本：Version 2.1.0 (1)，我按照你的描述，清空了hosts，自动更新的话，没有出现闪退，你进行了其他操作了吗？

**Comment by pjpjq** [comment]
我又下了一个最新版本, 也是直接自动更新就会闪退...

**Comment by ZzzM** [comment]
hosts清空了，出现闪退？

**Comment by pjpjq** [comment]
是的

**Comment by ZzzM** [comment]
@wendingp 我这边没问题，我再看看
