### ISSUE TITLE
2.2.2版本, 点网络更新一直失败啊

### ISSUE THREAD

**Issue by fcjxxl** [ZzzM/HostToolforMac#16]
2.2.2版本, 点网络更新一直失败啊

**Comment by ZzzM** [comment]
@fcjxxl 方便的话，把你的hosts发我一份？因为我这边能更新成功。

**Comment by ZzzM** [comment]
@fcjxxl 我现在更新一下逻辑吧，防止原hosts过长引起更新失败。现在第一次更新会全部覆盖，然后以后你就只要在“# 👇My Hosts👇”这下面添加就行了。

**Comment by ZzzM** [comment]
@fcjxxl 更新至v2.2.3，具体更新机制，我写了，可以看看

**Comment by fcjxxl** [comment]
好的3q, v2.2.3确实可以了
