### ISSUE TITLE
MAC OS客户端在哪里下载呢？没找到入口，一般Git上入口在哪里找啊

### ISSUE THREAD

**Issue by ugvf2009** [ZzzM/HostToolforMac#19]
谢谢！

**Comment by ZzzM** [comment]
![10681080-8c44-43e1-9495-b0a6ab1f32e9](https://user-images.githubusercontent.com/10611210/27898679-9b9e590e-6259-11e7-82b9-f7eaa5ab8d27.png)
下载完，直接使用里面的HostsToolForMac.app就行了

**Comment by wbget** [comment]
建议把这个写在readme.md那边，好找
