### ISSUE TITLE
打开https://google.com时错误

### ISSUE THREAD

**Issue by TianyiPeng** [ZzzM/HostToolforMac#20]
显示：
This page cannot be loaded using Chrome Data Saver. Try reloading the page.
Debug info: GET o-NmWeK0PIaBiwO8gKqwBg

**Comment by ZzzM** [comment]
@TianyiPeng https://google.com 我试了一下，没这个https://www.google.com 稳定

**Comment by november06** [comment]
Hi, 

I tried switching the hosts file on mac, but it seems not working for "https://gmail.com" and "https://google.com". And here is the output of a ping command:

$ ping gmail.com
PING gmail.com (216.58.220.192): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
...

Could you please tell me how to verify whether the hosts file is working (It seems working in my case) or how do we usually diagnose these kind of issue on mac? 

Thank you in advance. 
Shane

**Comment by ZzzM** [comment]
@november06 https://github.com/racaljk/hosts/issues,
It seems not available
