### ISSUE TITLE
刚下了最新版本，成功更新后hosts文件还是去年的

### ISSUE THREAD

**Issue by Jason4V** [ZzzM/HostToolforMac#24]
见下图
![wx20180201-105630](https://user-images.githubusercontent.com/385914/35659040-1857d0b2-073f-11e8-8012-37b2c4c955de.png)

**Comment by ZzzM** [comment]
@ImHUan 方便的话 把你的原 hosts 发我一份 ，我看看

**Comment by Jason4V** [comment]
er....已经手动覆盖了……
等我再更新不好的时候，给你发一下

**Comment by Jason4V** [comment]
[hosts.zip](https://github.com/ZzzM/HostsToolforMac/files/1761809/hosts.zip)
今天更新显示成功，但hosts还是旧的

**Comment by ZzzM** [comment]
我这边测试用的最新的版本，用你的 hosts 可以更新成功
@ImHUan 
![2 -28-2018 15-01-20](https://user-images.githubusercontent.com/10611210/36774291-63df9d8a-1c98-11e8-818d-918a6ca2fb05.gif)

**Comment by Jason4V** [comment]
奇怪了，难道是我macOS版本不是最新？

**Comment by ZzzM** [comment]
@ImHUan 
我的系统版本 ：10.13.3
HostsTool 版本：2.2.5(1)

**Comment by Jason4V** [comment]
原来是我在「设置更新」里错点成自定义更新了，实在抱歉！

再次感谢您这款作品给我们带来的便利性！
