### ISSUE TITLE
使用了镜像，但是没有权限

### ISSUE THREAD

**Issue by hbsun2113** [ZzzM/HostToolforMac#27]
![image](https://user-images.githubusercontent.com/27994442/67842929-10ca2600-fb36-11e9-9c77-d40eff6b2b1f.png)
另外，使用默认和jing xiang镜像的区别是什么？

**Comment by ZzzM** [comment]
感谢反馈，我这边会跟进的。
默认和镜像的区别：hosts 下载地址不一样而已

**Comment by Hansanshi** [comment]
@ZzzM 请问这个问题解决了吗？

**Comment by ZzzM** [comment]
@Hansanshi 你好，暂未解决该问题。10.15 之后，macOS 权限管理已做限制，正在找其他解决方案

**Comment by hbsun2113** [comment]
do not have a solution now

**Comment by ZzzM** [comment]
@hbsun2113 @Hansanshi 
v2.4.0 发布，已支持macOS Catalina，下载zip，解压即可使用
![WeChatefa98e840fd6f49d6e832b76cf647eee.png](http://ww1.sinaimg.cn/large/77a575a6gy1gag1nusnayj21jq0j8ace.jpg)
