### ISSUE TITLE
点击「云朵」图标在线更新hosts后会覆盖本地hosts原有的IP规则？

### ISSUE THREAD

**Issue by Jason4V** [ZzzM/HostToolforMac#6]
貌似把我之前的Adobe软件屏蔽的规则都覆盖了……
能否不覆盖呢？

**Comment by ZzzM** [comment]
@ImHUan 目前只能做覆盖操作，原先的规则需要备份再添加。你说的这个问题我会尝试优化一下

**Comment by Jason4V** [comment]
@ZzzM 哦这样，好的。那希望下个版本至少能在软件界面上有所说明吧，弹个对话框就行。

另外，非常感谢你开发的这个小工具，省了我很多事儿，多谢！

**Comment by ZzzM** [comment]
@ImHUan 优化了一下，可以保存原来ip，方便的话可以留个地址，给你发个刚改好的。后面的话，我感觉还可以加一个可以添加新ip的按钮。

**Comment by Jason4V** [comment]
@ZzzM  你怎么这么棒！ wanzhenhuan A gmail  多谢！

添加新IP的按钮想法也很好呀，如果能开机启动，默默自动后台更新就更好了！
