### ISSUE TITLE
关于：请检查导入的内容

### ISSUE THREAD

**Issue by ghost** [ZzzM/HostToolforMac#7]
关于HostsTool
在点击「hosts」载入新的主机时候，会一直显示 - 请检查导入的内容，以致于无法顺利刷新主机文件，请问是在我使用上有哪里出错了吗？之前是会成功的。 多谢

**Comment by ZzzM** [comment]
@PW-Chen 感谢你的及时反馈，最新的v2.0.7已经上传了，你可以去下载，如果新版本仍然存在问题，麻烦联系我

**Comment by ghost** [comment]
成功了！！
